### ISSUE TITLE
Pango::Font#get_coverage not available

### ISSUE THREAD

**Issue by mvz** [ruby-gnome/ruby-gnome#1020]
Hi,

In version 3.1.2, Pango has GI-based bindings. Unfortunately, `pango_font_get_coverage` is marked as not introspectable in the GIR, so Pango::Font#get_coverage is no longer available. I'm not sure why this method is marked not introspectable, it may have something to do with `Pango::Coverage` being 'disguised', but I'm not sure what that means in practice.

Does this this mean this method will have to be implemented in C? If so, I'll try to make a pull request.

**Comment by kou** [comment]
I build `Pango-1.0.gir` and get the following warnings for `pango_font_get_coverage`:

```text
fonts.c:1527: Warning: Pango: pango_font_get_coverage: unknown parameter 'language' in documentation comment, should be 'lang'
```

```text
fonts.c:1531: Warning: Pango: pango_font_get_coverage: return value: Invalid non-constant return of bare structure or union; register as boxed type or (skip)
```

The former can be fixed by the following patch:

```diff
diff --git a/pango/pango-font.h b/pango/pango-font.h
index cdc07cd0..d2623e95 100644
--- a/pango/pango-font.h
+++ b/pango/pango-font.h
@@ -609,7 +609,7 @@ struct _PangoFontClass
 
   PangoFontDescription *(*describe)           (PangoFont      *font);
   PangoCoverage *       (*get_coverage)       (PangoFont      *font,
-					       PangoLanguage  *lang);
+					       PangoLanguage  *language);
   PangoEngineShape *    (*find_shaper)        (PangoFont      *font,
 					       PangoLanguage  *lang,
 					       guint32         ch);
```

The latter will be fixed by making `PangoCoverage` `GBoxed`. It'll be easy to implement because `pango_coverage_ref()` and `pango_coverage_unref()` already exist. They will be able to use for `GBoxedCopyFunc` and `GBoxedFreeFunc`.

Could you report the patch for the former case to Pango developers at https://bugzilla.gnome.org/ ?

And could you implement `GBoxed` `PangoCoverage` and send a patch to Pango developers? Or could you report this issue to Pango developers?

**Comment by mvz** [comment]
Thanks for figuring this out, @kou. I'll create some patches/bug reports for Pango.

**Comment by mvz** [comment]
Bug reports here: https://bugzilla.gnome.org/show_bug.cgi?id=781852 and https://bugzilla.gnome.org/show_bug.cgi?id=781857

**Comment by kou** [comment]
Great!
