### ISSUE TITLE
Windows 10 - cannot use due to Nvidia card issue

### ISSUE THREAD

**Issue by iongion** [ruby-gnome/ruby-gnome#1121]
I just clean installed ruby for windows and gtk3 + gstreamer as instructed, I get this and I could not find anything helpful. The card is a GTX 1080 Ti.

fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").

My test is:
```
require "gtk3"
require "gst"
pipeline = Gst::Pipeline.new("pipeline")
source = Gst::ElementFactory.make("videotestsrc")
sink = Gst::ElementFactory.make("autovideosink")
pipeline << source << sink
source >> sink
pipeline.play()
```

What can it be ?

**Comment by kou** [comment]
It seems that `wined3d_guess_card` is a message from Wine. Why?

How about using `gtksink` instead of `autovideosink`:

```ruby
sink = Gst::ElementFactory.make("gtksink")
```

You can find available video sinks by the following script:

`ruby
require "gtk3"
require "gst"

spec = Gem::Specification.find_by_name("gstreamer")
system(File.join(spec.gem_dir, "vendor", "local", "bin", "gst-inspect-1.0", "--types", "Sink/Video"))
```

**Comment by kou** [comment]
No response.
