### ISSUE TITLE
Frozen string literal true (for ruby-gtk/ruby-gnome) by default?

### ISSUE THREAD

**Issue by ghost** [ruby-gnome/ruby-gnome#1153]
Hello,

This goes mostly to kou and cedlemo since they appear to be the two
who do the most right now. But of course, it also goes to everyone else
who may add/change/contribute code to the ruby-gtk/gnome bindings
or may just be using ruby-gtk/gnome anyway. :)

My question is:

- Should we change the .rb files, where relevant, towards frozen string 
literal true, such as via:

    frozen_string_literal: true (with a leading '#'; markdown here gets confused so I omitted it)

?

The net benefit may not be huge, in particular for short code, but for
larger applications, there may be a small but noticable speed gain.

For example, here:

https://git.ruby-lang.org/ruby.git/commit/?id=d3d40e99f12a6636150989915f3506fcae407945

The speed gain-improvement for *rdoc* was at about ~5%. Which is small but not bad
I think.

(A lot of this work is, by the way, quite easy for other people to contribute to and get
involved into ruby-gtk. I just would like to ask what you guys think about it. I have not
looked at all .rb files to see whether there may be any substantial gain from this, so
this is another reason why I ask here. Feel free to close this issue here at any moment
in time; I'll close it in perhaps a month or so, give or take, if I don't forget, or perhaps
earlier if statements come early too, or if we already finished with the task at hand.)

One question I may have is - if this is given the ok, what header should we use for
.rb files then?

I personally use this header:

```ruby
#!/System/Index/bin/ruby -w
# Encoding: ISO-8859-1
# frozen_string_literal: true
```

But of course this is not useful for other people since it is a customized shebang,
then an encoding that is not UTF-8 (so I think we should use UTF-8), before the
last line is a frozen string literal. Would frozen string literal on the very first
line of a .rb file be sufficient? I have not tried yet but this may be the simplest
solution there.

Thanks for reading!

**Comment by kou** [comment]
I'm not positive adding `frozen_string_literal: true` because it's not big effort for performance and increasing our works.
But I don't object that someone works on it.

We add shebang only when the file should be executable. It means that we never add shebang to files in `lib/`. We add shebang to `gtk3/sample/gtk-demo/main.rb` but don't add add shebang to `gtk3/sample/gtk-demo/dialog.rb`.

We never add `encoding:` when the file contains only ASCII characters. If we need to use non-ASCII characters, we prefer to UTF-8. If we use UTF-8, we add `# -*- coding: utf-8 -*-`. It's suitable both for Ruby and Emacs.
