### ISSUE TITLE
Rename ruby-gnome2. 

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome/ruby-gnome#1277]
This is not a priority issue.

I am a newcomer and could not understand the meaning of 2 in the name of this repository.
The naming is very confusing. Neither ruby-gnome1 nor ruby-gnome exists.

I may have to respect the pioneers.
Evolution of ruby-gnome2 (Gource Visualization)
https://www.youtube.com/watch?v=fXEg9REPdC0

But, someone has to suggest rename.

**Comment by kou** [comment]
We should choose "ruby-gnome" as project ID and "Ruby-GNOME" as project name.

**Comment by rubyFeedback** [comment]
i think renaming it would be a good idea, even though this is not hugely important (more important to see that the bindings work).

Dropping the version would be a good idea, IMO. We could also adopt something similar to what GTK does upstream, like here:

https://www.gtk.org/language-bindings.php

Something like a HTML table to show which versions are supported.

Something like this could then also be used for the gnome-addons. Ideally we could generate this automatically from some data (perhaps .gemspec since most of the gems are on rubygems.org too).

One advantage of e. g. a HTML table would be that newcomers could go to that page and quickly see which version of ruby+gtk/gnome may be supported. I myself have most ruby-specific code still at gtk2, although I am very, very slowly transitioning into gtk3.

**Comment by kou** [comment]
Done.

**Comment by kojix2** [comment]
Great!
