### ISSUE TITLE
Minor proposal: extend set_size_request() to allow a Hash as argument, containing width: and height:

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1406]
Hello rubygnome maintainers,

I would like to propose extending the method called:

    set_size_request()

To specifically allow for:

    WIDTH  = 1020
    HEIGHT =  800

    set_size_request(
      width: WIDTH,
      height: HEIGHT
    )

Right now if I do so, I get an error:

    control_panel.rb:38:in `set_size_request': wrong number of arguments (given 1, expected 2) (ArgumentError)

No surprise, as set_size_request() wants two integer values.

But I would like to use a Hash instead; that may also allow
me to pass such hashes between different widgets, scale/modify
height and width and so forth. I am also aware of subclassing
and then making changes, but I would prefer to have this 
functionality within ruby-gtk, if that would be possible, by
default.

In other words: this proposal would like to suggest to also allow
a Hash to be used there, in ADDITION to the two integer values
necessary.

The old way, passing two integers, should be preserved, to avoid
any potential backwards incompatibility. (I don't want to break
anyone's scripts with this suggestion, that is why the old behaviour
should also be retained.)

Reasoning for this proposal:

I often forget whether it is height first or width first so it would
be nice if ruby-gtk could support a Hash as well. That way I specify
:height and :width and don't have to remember the order. (There have 
been a few other changes towards hash inclusion in the past, e. g.
GdkPixbuf and I think :file or :path or something like that.)

I prefer a Hash because keyword arguments are, as far as I understood
it, less flexible than oldschool option hash.

In the long run, I think it would be nice if the ruby-gtk bindings could
also get a bit more "ruby-esque" flexibility (e. g. allow for more 
symbol names rather than harcoded ::Gtk::SomeWidget::SOME_CONSTANT),
but I totally understand lack of resources, time and so forth, so 
no worries if this can not be changed; ruby-gtk is one of the few
ruby GUI toolkits that is actually still alive. tk became a standalone
gem and is probably only in bug-fix mode, ruby-qt became inactive a
long time ago, ruby-wxwidgets depends mostly just on hanmac and he
does not seem to have a lot of time these days.

With gtk4 coming eventually, hopefully ruby-gtk can still live and
prosper. (I am still using ruby-gtk2 mostly, but I am finally VERY
slowly changing towards gtk3 ... it's surprisingly much work.
Anyway, sorry for the off-topic comments there. Please feel free
to close this issue at any moment in time for any reason.)

PS: I forgot one thing. What happens if a user does not specify
both width: and height: when giving a Hash? I believe in this case
the correct behaviour would be to notify the user that this is
wrong, similar to how set_size_request() fails if you provide
only one argument - so the behaviour should be synced/the same
in such a case.

**Comment by kojix2** [comment]
The core of ruby-gnome is gobject-introspection. Many bindings are automatically generated by gobject-introspection. 
Another gem that supports gobject-intorospection is gir_ffi. 

Ruby/Gtk is maintained by @kou's extraordinary efforts. Most of that effort is to support gobject-introspection.
ruby-gnome is not very Ruby-like. That's because most bindings are generated automatically. 
Therefore, any customization beyond what gobject-introspection produces can be difficult to maintain.

Some methods look like Ruby, but they are early works, and some aspects continue for backward compatibility, I think.

**Comment by kou** [comment]
I've added support for `{width:, height:}` to only gtk3 gem. It's not added to gtk2 gem.
It's easy to implement it in gtk3 gem because it's based on GObject Introspection. We can custom API by Ruby.
gtk2 gem is implemented by C. We should use C to implement such API. (We can use Ruby for it but using C is recommended way.)

**Comment by kou** [comment]
BTW, we can release gtk4 gem once GTK 4 is released.
We're already working on it: https://github.com/ruby-gnome/ruby-gnome/tree/master/gtk4
