### ISSUE TITLE
default theme is hard to see (GTK4 on Windows - maybe installation problem?)

### ISSUE THREAD

**Issue by HuBandiT** [ruby-gnome/ruby-gnome#1446]
Greetings,

A simple application with just a Paned, a Frame, a few labels and a Scale looks like this:

![kép](https://user-images.githubusercontent.com/10346452/139159409-76cbb282-bb3c-4a74-abbc-c39eaca0fca0.png)

I find this quite hard to see - type is very small, and elements are washed out, especially the Scale (which is between the two bottom labels "alma" and "körte") is barely visible.

Is this expected behaviour? Am I just missing some theme initialization step to make things look more visible? Or is this perhaps an install issue?

Thank you in advance.

**Comment by Speak2Erase** [comment]
I believe this could be because GTK is declaring itself as high DPI when it is not, and Windows deciding not to scale it. You can fix this by forcing Windows to enforce scaling.

Find `gdbus.exe` and `ruby.exe` and for both of them go to

`Properties->Compatibility->Change high DPI settings`
`Check Override high DPI scaling behavior`
`Set the dropdown to System (Enhanced)`
