### ISSUE TITLE
Inconsistency between registered and unregistered types

### ISSUE THREAD

**Issue by D-W-L** [ruby-gnome/ruby-gnome#1544]
Sub-classes of Gtk::Box, Gtk::Scrollbar and maybe other (these are the ones I found on a short search), expect different `super` parameters, depending if the subclass is is registered to the GObject system, or not.

An example:
```
#!/usr/bin/env ruby

require 'gtk3'

class Aaa < Gtk::Box
    def initialize
        super :vertical
    end
end


class Bbb < Gtk::Box
    type_register
    def initialize
        super :vertical
    end
end

win = Gtk::Window.new
box = Gtk::Box.new :horizontal
a = Aaa.new
b = Bbb.new
box.pack_start a
box.pack_start b
win << box
win.show_all


Gtk.main
```

and the shell output:
```
box.rb:15:in `initialize': wrong argument type Symbol (expected Hash) (TypeError)
	from box.rb:15:in `initialize'
	from box.rb:22:in `new'
	from box.rb:22:in `<main>'
```

class Aaa work like expected, Bbb not. It expects as `super` parameter  `:orientation => :horizontal`
Is it my misunderstanding or a bug?

**Comment by kou** [comment]
It's intentional.

You can't use base class's constructor because base class's constructor uses base class's `GType`. For example, [`gtk_box_new()`](https://docs.gtk.org/gtk3/ctor.Box.new.html) always uses `GTK_TYPE_BOX` not `Aaa`/`Bbb`'s `GType`.

You must specify [properties](https://docs.gtk.org/gtk3/class.Box.html#properties) explicitly:

```ruby
class Bbb < Gtk::Box
    type_register
    def initialize
        super orientation: :vertical
    end
end
```
